### ISSUE TITLE
Admins shouldn't be able to delete themselves nor to edit their accounts

### ISSUE THREAD

**Issue by matthewslouismarie** [jameshmread/YOYO-Industrial-Team-Project#43]
It doesn't really make sense to allow administrators to delete their accounts, this can lead to mistakes. Besides, any user can already edit their profiles. So allowing administrators to edit their profiles from the "Manage users" is redundant and a bit confusing.

**Comment by ghost** [comment]
Going to leave this until after Monday for client demo

**Comment by tomcatooo** [comment]
commited with pull request made, Delete button is disabled for admin users.

**Comment by tomcatooo** [comment]
Need to discuss the removal of the edit for admins as they should also be able to alter their own report frequency if necessary from the admin panel
