### ISSUE TITLE
Fix “page expired” when updating profile

### ISSUE THREAD

**Issue by matthewslouismarie** [jameshmread/YOYO-Industrial-Team-Project#44]
I get a "Page Expired" when updating my profile.
It reads: 

> The page has expired due to inactivity.
> Please refresh and try again.

**Comment by tomcatooo** [comment]
This occurs when both the name and email are updated, working on this now.

**Comment by jameshmread** [comment]
Cannot be reproduced

**Comment by matthewslouismarie** [comment]
Fascist
