### ISSUE TITLE
Remove welcome page and change colour scheme

### ISSUE THREAD

**Issue by jameshmread** [jameshmread/YOYO-Industrial-Team-Project#48]
The welcome page is not necessary and the colour scheme should probably be 'yoyo pink' and another complimentary colour. I found a blue which was nice

The pink i have is `#DA04A4` (have not verified if this is the exact brand colour)
Complimentary Blue `#007bff`

EDIT:
Each store owner / user should be able to set their store colours

**Comment by ghost** [comment]
Agreed, the two are rather complimentary. Perhaps having an option to select store colours too?
