### ISSUE TITLE
Move angular swapping logic to blade navbar

### ISSUE THREAD

**Issue by ghost** [jameshmread/YOYO-Industrial-Team-Project#52]
To ensure that the angular app doesn't have to change too much, if possible could the logic for swapping between graph datasets be move the angular.blade.php found in layouts.

I've marked the nav bar button in blue which would perform the actions of the angular button circled in blue.

![capture](https://user-images.githubusercontent.com/17427848/30785053-19bd14e6-a158-11e7-882e-1a6696a68caf.PNG)

**Comment by jameshmread** [comment]
No longer using angular
